/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MazAvatar: typeof import('maz-ui/components/MazAvatar')['default']
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazCard: typeof import('maz-ui/components/MazCard')['default']
    MazCardSpotlight: typeof import('maz-ui/components/MazCardSpotlight')['default']
    MazInput: typeof import('maz-ui/components/MazInput')['default']
    MazSpotlightCard: typeof import('maz-ui/components/MazSpotlightCard')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vTooltip: typeof import('maz-ui')['vTooltip']
  }
}
