/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MazBtn: typeof import('maz-ui/components/MazBtn')['default']
    MazButton: typeof import('maz-ui/components/MazButton')['default']
    MazCheckbox: typeof import('maz-ui/components/MazCheckbox')['default']
    MazInput: typeof import('maz-ui/components/MazInput')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
